# Generated by Django 5.0.6 on 2024-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="mc_supermanager",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=510, null=True, verbose_name="管理员姓名"
                    ),
                ),
            ],
            options={
                "verbose_name": "系统管理员",
                "verbose_name_plural": "系统管理员",
                "db_table": "supermanager",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_userinfo",
            fields=[
                (
                    "userid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="用户ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=520, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "useremail",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="用户邮箱"
                    ),
                ),
                (
                    "userpkwkwasswkwkword",
                    models.CharField(
                        blank=True, max_length=470, null=True, verbose_name="用户密码"
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True, max_length=455, null=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=855, null=True, verbose_name="性别"
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "regkwkwisterdate",
                    models.DateField(blank=True, null=True, verbose_name="注册日期"),
                ),
                (
                    "userrole",
                    models.CharField(
                        blank=True, max_length=910, null=True, verbose_name="用户角色"
                    ),
                ),
                (
                    "lkwkwastlogkwkwintime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信息表",
                "verbose_name_plural": "用户信息表",
                "db_table": "userinfo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_userpermkwkwission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=880, null=True, verbose_name="关联用户ID"
                    ),
                ),
                (
                    "permkwkwissionid",
                    models.CharField(
                        blank=True, max_length=715, null=True, verbose_name="关联权限ID"
                    ),
                ),
                (
                    "rolename",
                    models.CharField(
                        blank=True, max_length=950, null=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "permkwkwissionname",
                    models.CharField(
                        blank=True, max_length=940, null=True, verbose_name="权限名称"
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "isactive",
                    models.BooleanField(blank=True, null=True, verbose_name="是否激活"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "用户权限表",
                "verbose_name_plural": "用户权限表",
                "db_table": "userpermkwkwission",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_userwatchhkwkwistkwkwory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=605, null=True, verbose_name="关联用户ID"
                    ),
                ),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=675, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "watchtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="观看时间"
                    ),
                ),
                (
                    "watchduration",
                    models.CharField(
                        blank=True, max_length=990, null=True, verbose_name="观看时长"
                    ),
                ),
                (
                    "watchstatus",
                    models.CharField(
                        blank=True,
                        max_length=980,
                        null=True,
                        verbose_name="观看状态如已观看、观看中、暂停、已放弃",
                    ),
                ),
                (
                    "ratkwkwing",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="评分可选用户对该视频的评分"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="评论可选用户对该视频的评论"
                    ),
                ),
                (
                    "likestatus",
                    models.CharField(
                        blank=True,
                        max_length=685,
                        null=True,
                        verbose_name="点赞状态如已点赞、未点赞",
                    ),
                ),
                (
                    "sharestatus",
                    models.CharField(
                        blank=True,
                        max_length=465,
                        null=True,
                        verbose_name="分享状态如已分享、未分享",
                    ),
                ),
                (
                    "favkwkworitestatus",
                    models.CharField(
                        blank=True,
                        max_length=890,
                        null=True,
                        verbose_name="收藏状态如已收藏、未收藏",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户观看历史表",
                "verbose_name_plural": "用户观看历史表",
                "db_table": "userwatchhkwkwistkwkwory",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoadinfo",
            fields=[
                (
                    "categkwkworyid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="广告分类ID",
                    ),
                ),
                (
                    "advertkwkwiserid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="广告主ID",
                    ),
                ),
                (
                    "videoadid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="视频广告ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=865, null=True, verbose_name="广告标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="广告描述"),
                ),
                (
                    "starttime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "endtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "videourl",
                    models.URLField(blank=True, null=True, verbose_name="视频链接"),
                ),
                (
                    "thumbnailurl",
                    models.URLField(blank=True, null=True, verbose_name="缩略图链接"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=710, null=True, verbose_name="广告状态"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频广告信息表",
                "verbose_name_plural": "视频广告信息表",
                "db_table": "videoadinfo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoadplayreckwkword",
            fields=[
                (
                    "videoadid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="视频广告ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "playtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="播放时间"
                    ),
                ),
                (
                    "playduration",
                    models.CharField(
                        blank=True, max_length=895, null=True, verbose_name="播放时长"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True,
                        max_length=810,
                        null=True,
                        verbose_name="用户ID关联用户",
                    ),
                ),
                (
                    "devicetype",
                    models.CharField(
                        blank=True, max_length=630, null=True, verbose_name="设备类型"
                    ),
                ),
                (
                    "ipaddressip",
                    models.TextField(blank=True, null=True, verbose_name="地址"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=430, null=True, verbose_name="地理位置"
                    ),
                ),
                (
                    "playstatus",
                    models.CharField(
                        blank=True,
                        max_length=570,
                        null=True,
                        verbose_name="播放状态如成功、失败、中断等",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频广告播放记录表",
                "verbose_name_plural": "视频广告播放记录表",
                "db_table": "videoadplayreckwkword",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoanalyskwkwismetrics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True,
                        max_length=905,
                        null=True,
                        verbose_name="视频ID关联视频",
                    ),
                ),
                (
                    "analyskwkwistime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="分析时间"
                    ),
                ),
                (
                    "viewcount",
                    models.CharField(
                        blank=True, max_length=725, null=True, verbose_name="观看次数"
                    ),
                ),
                (
                    "likecount",
                    models.CharField(
                        blank=True, max_length=950, null=True, verbose_name="点赞次数"
                    ),
                ),
                (
                    "sharecount",
                    models.CharField(
                        blank=True, max_length=660, null=True, verbose_name="分享次数"
                    ),
                ),
                (
                    "commentcount",
                    models.TextField(blank=True, null=True, verbose_name="评论次数"),
                ),
                (
                    "bouncerate",
                    models.CharField(
                        blank=True, max_length=900, null=True, verbose_name="跳出率"
                    ),
                ),
                (
                    "averagewatchtime",
                    models.CharField(
                        blank=True,
                        max_length=910,
                        null=True,
                        verbose_name="平均观看时长",
                    ),
                ),
                (
                    "engagementrate",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="互动率"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频分析指标表",
                "verbose_name_plural": "视频分析指标表",
                "db_table": "videoanalyskwkwismetrics",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoauditstatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True,
                        max_length=865,
                        null=True,
                        verbose_name="视频ID关联字段指向视频的ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=980,
                        null=True,
                        verbose_name="审核状态如待审核、审核通过、审核拒绝",
                    ),
                ),
                (
                    "reviewerid",
                    models.CharField(
                        blank=True,
                        max_length=820,
                        null=True,
                        verbose_name="审核员ID关联字段指向审核员的ID",
                    ),
                ),
                (
                    "reviewtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "rejectrekwkwason",
                    models.CharField(
                        blank=True,
                        max_length=700,
                        null=True,
                        verbose_name="拒绝原因如果状态为审核拒绝则记录拒绝的具体原因",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=980, null=True, verbose_name="审核备注"
                    ),
                ),
                (
                    "kwkwisfkwkwinal",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否最终审核标记该审核是否为最终审核结果",
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatedat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频审核状态表",
                "verbose_name_plural": "视频审核状态表",
                "db_table": "videoauditstatus",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videocategkwkwory",
            fields=[
                (
                    "parentid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="父分类ID用于构建分类层级如果为顶级分类则为NULL",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=790, null=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="分类描述"),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "kwkwisactive",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否激活用于控制分类是否显示在前端",
                    ),
                ),
                (
                    "skwkwortorder",
                    models.CharField(
                        blank=True, max_length=750, null=True, verbose_name="排序顺序"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频分类表",
                "verbose_name_plural": "视频分类表",
                "db_table": "videocategkwkwory",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videocomment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=490, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=895, null=True, verbose_name="关联用户ID"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="评论内容"),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "likecount",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="点赞数"
                    ),
                ),
                (
                    "replycount",
                    models.CharField(
                        blank=True, max_length=620, null=True, verbose_name="回复数"
                    ),
                ),
                (
                    "kwkwiskwkwdeleted",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否已删除"
                    ),
                ),
                (
                    "parentid",
                    models.CharField(
                        blank=True,
                        max_length=765,
                        null=True,
                        verbose_name="关联父评论ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频评论表",
                "verbose_name_plural": "视频评论表",
                "db_table": "videocomment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videocopyrightinfo",
            fields=[
                (
                    "relatedvideoid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="相关视频ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=850, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "copyrightholder",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="版权持有人"
                    ),
                ),
                (
                    "copyrightyear",
                    models.CharField(
                        blank=True, max_length=455, null=True, verbose_name="版权年份"
                    ),
                ),
                (
                    "licensetype",
                    models.CharField(
                        blank=True, max_length=675, null=True, verbose_name="许可类型"
                    ),
                ),
                (
                    "licensestatus",
                    models.CharField(
                        blank=True, max_length=525, null=True, verbose_name="许可状态"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="版权描述"),
                ),
                (
                    "creationdate",
                    models.DateField(blank=True, null=True, verbose_name="创建日期"),
                ),
                (
                    "modkwkwificationdate",
                    models.DateField(blank=True, null=True, verbose_name="修改日期"),
                ),
            ],
            options={
                "verbose_name": "视频版权信息表",
                "verbose_name_plural": "视频版权信息表",
                "db_table": "videocopyrightinfo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videocoverimage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True,
                        max_length=880,
                        null=True,
                        verbose_name="视频ID关联字段指向视频的",
                    ),
                ),
                (
                    "coverimageurl",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="58027",
                        verbose_name="封面图片URL",
                    ),
                ),
                (
                    "imagekwkwfkwkwormat",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="58028",
                        verbose_name="图片格式",
                    ),
                ),
                (
                    "imagesize",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="58029",
                        verbose_name="图片大小单位KB",
                    ),
                ),
                (
                    "uploadtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="上传时间"
                    ),
                ),
                (
                    "creatkwkworid",
                    models.CharField(
                        blank=True,
                        max_length=460,
                        null=True,
                        verbose_name="创建者ID关联字段指向用户的",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=590,
                        null=True,
                        verbose_name="状态例如有效、无效、待审核",
                    ),
                ),
                (
                    "description",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="58033",
                        verbose_name="图片描述",
                    ),
                ),
                (
                    "kwkwiskwkwdefault",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否为默认封面kwTruekwFalse",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频封面图片表",
                "verbose_name_plural": "视频封面图片表",
                "db_table": "videocoverimage",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videodanmu",
            fields=[
                (
                    "userid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="发送弹幕的用户唯一标识符关联用户",
                    ),
                ),
                (
                    "videoid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="视频唯一标识符关联视频",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "danmucontent",
                    models.TextField(blank=True, null=True, verbose_name="弹幕内容"),
                ),
                (
                    "sendtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "colkwkwor",
                    models.CharField(
                        blank=True, max_length=410, null=True, verbose_name="弹幕颜色"
                    ),
                ),
                (
                    "fontsize",
                    models.CharField(
                        blank=True, max_length=860, null=True, verbose_name="字体大小"
                    ),
                ),
                (
                    "kwkwisvkwkwisible",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否可见用于控制弹幕的显示与隐藏",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        max_length=880,
                        null=True,
                        verbose_name="弹幕位置如顶部、底部、滚动等",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        max_length=890,
                        null=True,
                        verbose_name="弹幕显示时长秒",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频弹幕表",
                "verbose_name_plural": "视频弹幕表",
                "db_table": "videodanmu",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videodanmublockwkwkwords",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "wkwkword",
                    models.CharField(
                        blank=True, max_length=475, null=True, verbose_name="屏蔽词"
                    ),
                ),
                (
                    "videoid",
                    models.CharField(
                        blank=True,
                        max_length=930,
                        null=True,
                        verbose_name="视频ID关联字段指向视频的ID",
                    ),
                ),
                (
                    "creatkwkworid",
                    models.CharField(
                        blank=True,
                        max_length=840,
                        null=True,
                        verbose_name="创建者ID关联字段指向用户的ID",
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "kwkwisactive",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否激活用于控制屏蔽词是否生效",
                    ),
                ),
                (
                    "blocktype",
                    models.CharField(
                        blank=True,
                        max_length=470,
                        null=True,
                        verbose_name="屏蔽类型如关键词、正则达式等",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="描述对屏蔽词的额外说明或备注",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频弹幕屏蔽词表",
                "verbose_name_plural": "视频弹幕屏蔽词表",
                "db_table": "videodanmublockwkwkwords",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoerrkwkworlog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=410, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "errkwkwortype",
                    models.CharField(
                        blank=True, max_length=995, null=True, verbose_name="错误类型"
                    ),
                ),
                (
                    "errkwkwordescription",
                    models.TextField(blank=True, null=True, verbose_name="错误描述"),
                ),
                (
                    "errkwkwortime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="错误时间"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否已解决"
                    ),
                ),
                (
                    "resolvedtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "resolvedby",
                    models.CharField(
                        blank=True, max_length=715, null=True, verbose_name="关联解决人"
                    ),
                ),
                (
                    "devicekwkwinfo",
                    models.CharField(
                        blank=True, max_length=515, null=True, verbose_name="设备信息"
                    ),
                ),
                (
                    "clientip",
                    models.CharField(
                        blank=True, max_length=955, null=True, verbose_name="客户端IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频错误日志表",
                "verbose_name_plural": "视频错误日志表",
                "db_table": "videoerrkwkworlog",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videofilestkwkworage",
            fields=[
                (
                    "videoid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="视频ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "filename",
                    models.FileField(
                        blank=True, null=True, upload_to="57925", verbose_name="文件名"
                    ),
                ),
                (
                    "filepath",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="57926",
                        verbose_name="文件存储路径",
                    ),
                ),
                (
                    "filesize",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="57927",
                        verbose_name="文件大小单位MB",
                    ),
                ),
                (
                    "uploadtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="上传时间"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        max_length=550,
                        null=True,
                        verbose_name="视频时长单位秒",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        max_length=630,
                        null=True,
                        verbose_name="分辨率例如1920x1080",
                    ),
                ),
                (
                    "kwkwfkwkwormat",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="视频格式例如mp4",
                    ),
                ),
                (
                    "creatkwkworid",
                    models.CharField(
                        blank=True,
                        max_length=890,
                        null=True,
                        verbose_name="创建者ID关联用户",
                    ),
                ),
                (
                    "categkwkworyid",
                    models.CharField(
                        blank=True,
                        max_length=900,
                        null=True,
                        verbose_name="分类ID关联视频分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频文件存储表",
                "verbose_name_plural": "视频文件存储表",
                "db_table": "videofilestkwkworage",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoinfo",
            fields=[
                (
                    "videoid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="视频ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videotitle",
                    models.CharField(
                        blank=True, max_length=915, null=True, verbose_name="视频标题"
                    ),
                ),
                (
                    "videodescription",
                    models.TextField(blank=True, null=True, verbose_name="视频描述"),
                ),
                (
                    "uploadtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="上传时间"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=720, null=True, verbose_name="视频时长秒"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True, max_length=760, null=True, verbose_name="视频分辨率"
                    ),
                ),
                (
                    "filetype",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="57905",
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "filesize",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="57906",
                        verbose_name="文件大小KBMBGB",
                    ),
                ),
                (
                    "creatkwkworid",
                    models.CharField(
                        blank=True,
                        max_length=515,
                        null=True,
                        verbose_name="创建者ID关联用户",
                    ),
                ),
                (
                    "categkwkworyid",
                    models.CharField(
                        blank=True,
                        max_length=675,
                        null=True,
                        verbose_name="类别ID关联视频类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频信息表",
                "verbose_name_plural": "视频信息表",
                "db_table": "videoinfo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videolike",
            fields=[
                (
                    "deviceid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="设备ID可选用于追踪用户设备",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=405, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=995, null=True, verbose_name="关联用户ID"
                    ),
                ),
                (
                    "liketime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="点赞时间"
                    ),
                ),
                (
                    "kwkwisliked",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否点赞1为已点赞0为未点赞用于取消点赞功能",
                    ),
                ),
                (
                    "ipaddress",
                    models.TextField(
                        blank=True, null=True, verbose_name="点赞时的IP地址"
                    ),
                ),
                (
                    "liketype",
                    models.CharField(
                        blank=True,
                        max_length=965,
                        null=True,
                        verbose_name="点赞类型如普通点赞、特殊点赞等可用枚举或示",
                    ),
                ),
                (
                    "platkwkwfkwkworm",
                    models.CharField(
                        blank=True,
                        max_length=890,
                        null=True,
                        verbose_name="点赞平台如Web、iOS、Android等",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频点赞表",
                "verbose_name_plural": "视频点赞表",
                "db_table": "videolike",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videomatrixconfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "matrixname",
                    models.CharField(
                        blank=True,
                        max_length=555,
                        null=True,
                        verbose_name="视频矩阵名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述信息"),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatedat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "videosourceid",
                    models.CharField(
                        blank=True,
                        max_length=845,
                        null=True,
                        verbose_name="视频源ID关联视频源",
                    ),
                ),
                (
                    "outputchannelid",
                    models.CharField(
                        blank=True,
                        max_length=870,
                        null=True,
                        verbose_name="输出通道ID关联输出通道",
                    ),
                ),
                (
                    "layoutconfig",
                    models.CharField(
                        blank=True,
                        max_length=725,
                        null=True,
                        verbose_name="布局配置如1x4",
                    ),
                ),
                (
                    "kwkwisactive",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否激活用于控制视频矩阵的启用状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频矩阵配置表",
                "verbose_name_plural": "视频矩阵配置表",
                "db_table": "videomatrixconfig",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videomatrixnode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nodename",
                    models.CharField(
                        blank=True, max_length=550, null=True, verbose_name="节点名称"
                    ),
                ),
                (
                    "videosourceid",
                    models.CharField(
                        blank=True,
                        max_length=930,
                        null=True,
                        verbose_name="关联视频源ID",
                    ),
                ),
                (
                    "videokwkwfkwkwormat",
                    models.CharField(
                        blank=True, max_length=415, null=True, verbose_name="视频格式"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True, max_length=820, null=True, verbose_name="分辨率"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=860,
                        null=True,
                        verbose_name="状态如在线、离线、维护中",
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "parentnodeid",
                    models.CharField(
                        blank=True,
                        max_length=575,
                        null=True,
                        verbose_name="关联父节点ID用于示节点之间的层级关系",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述信息"),
                ),
            ],
            options={
                "verbose_name": "视频矩阵节点表",
                "verbose_name_plural": "视频矩阵节点表",
                "db_table": "videomatrixnode",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videomatrixplayreckwkword",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True,
                        max_length=410,
                        null=True,
                        verbose_name="视频ID关联视频",
                    ),
                ),
                (
                    "matrixid",
                    models.CharField(
                        blank=True,
                        max_length=565,
                        null=True,
                        verbose_name="矩阵ID关联视频矩阵",
                    ),
                ),
                (
                    "playtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="播放时间"
                    ),
                ),
                (
                    "playduration",
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name="播放时长秒"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True,
                        max_length=855,
                        null=True,
                        verbose_name="用户ID关联用户",
                    ),
                ),
                (
                    "deviceid",
                    models.CharField(
                        blank=True,
                        max_length=735,
                        null=True,
                        verbose_name="设备ID关联设备",
                    ),
                ),
                (
                    "playstatus",
                    models.CharField(
                        blank=True,
                        max_length=765,
                        null=True,
                        verbose_name="播放状态如成功、失败、中断等",
                    ),
                ),
                (
                    "ipaddress",
                    models.TextField(
                        blank=True, null=True, verbose_name="播放请求的IP地址"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频矩阵播放记录表",
                "verbose_name_plural": "视频矩阵播放记录表",
                "db_table": "videomatrixplayreckwkword",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videomultilkwkwingualsubtitles",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=615, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "languagecode",
                    models.CharField(
                        blank=True, max_length=640, null=True, verbose_name="语言代码"
                    ),
                ),
                (
                    "subtitletext",
                    models.TextField(blank=True, null=True, verbose_name="字幕文本"),
                ),
                (
                    "starttime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="开始时间字幕出现时间",
                    ),
                ),
                (
                    "endtime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="结束时间字幕消失时间",
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatedat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "kwkwisactive",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否激活用于控制字幕是否显示在视频中",
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True,
                        max_length=425,
                        null=True,
                        verbose_name="创建者用户ID关联到用户示谁添加了这条字幕",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频多语言字幕表",
                "verbose_name_plural": "视频多语言字幕表",
                "db_table": "videomultilkwkwingualsubtitles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoplayreckwkword",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True,
                        max_length=835,
                        null=True,
                        verbose_name="视频ID关联视频信息",
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True,
                        max_length=805,
                        null=True,
                        verbose_name="用户ID关联用户信息",
                    ),
                ),
                (
                    "playstarttime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="播放开始时间"
                    ),
                ),
                (
                    "playendtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="播放结束时间"
                    ),
                ),
                (
                    "playduration",
                    models.CharField(
                        blank=True, max_length=710, null=True, verbose_name="播放时长秒"
                    ),
                ),
                (
                    "playstatus",
                    models.CharField(
                        blank=True,
                        max_length=565,
                        null=True,
                        verbose_name="播放状态如已完成、暂停、中断",
                    ),
                ),
                (
                    "devicetype",
                    models.CharField(
                        blank=True,
                        max_length=785,
                        null=True,
                        verbose_name="设备类型如手机、平板、电脑",
                    ),
                ),
                (
                    "ipaddress",
                    models.TextField(blank=True, null=True, verbose_name="IP地址"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=515,
                        null=True,
                        verbose_name="播放位置可选根据IP解析的地理位置",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频播放记录表",
                "verbose_name_plural": "视频播放记录表",
                "db_table": "videoplayreckwkword",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videopopularity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=580, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "viewcount",
                    models.CharField(
                        blank=True, max_length=945, null=True, verbose_name="观看次数"
                    ),
                ),
                (
                    "likecount",
                    models.CharField(
                        blank=True, max_length=785, null=True, verbose_name="点赞次数"
                    ),
                ),
                (
                    "sharecount",
                    models.CharField(
                        blank=True, max_length=745, null=True, verbose_name="分享次数"
                    ),
                ),
                (
                    "commentcount",
                    models.TextField(blank=True, null=True, verbose_name="评论次数"),
                ),
                (
                    "popularitysckwkwore",
                    models.IntegerField(blank=True, null=True, verbose_name="热度评分"),
                ),
                (
                    "publkwkwishtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "categkwkworyid",
                    models.CharField(
                        blank=True, max_length=885, null=True, verbose_name="关联类别ID"
                    ),
                ),
                (
                    "creatkwkworid",
                    models.CharField(
                        blank=True,
                        max_length=910,
                        null=True,
                        verbose_name="关联创作者ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频热度统计表",
                "verbose_name_plural": "视频热度统计表",
                "db_table": "videopopularity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoqualityassessment",
            fields=[
                (
                    "relatedkwkwissueid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="相关问题ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=565, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "qualitysckwkwore",
                    models.IntegerField(blank=True, null=True, verbose_name="质量评分"),
                ),
                (
                    "kwkwassessmenttime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="评估时间"
                    ),
                ),
                (
                    "reviewerid",
                    models.CharField(
                        blank=True,
                        max_length=715,
                        null=True,
                        verbose_name="关联评审员ID",
                    ),
                ),
                (
                    "framerate",
                    models.CharField(
                        blank=True, max_length=730, null=True, verbose_name="帧率"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True, max_length=445, null=True, verbose_name="分辨率"
                    ),
                ),
                (
                    "bitrate",
                    models.CharField(
                        blank=True, max_length=675, null=True, verbose_name="比特率"
                    ),
                ),
                (
                    "encodkwkwingkwkwfkwkwormat",
                    models.CharField(
                        blank=True, max_length=665, null=True, verbose_name="编码格式"
                    ),
                ),
                (
                    "ckwkworruptiondetected",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否检测到损坏"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频质量评估表",
                "verbose_name_plural": "视频质量评估表",
                "db_table": "videoqualityassessment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videorecommendationparams",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "algkwkworithmname",
                    models.CharField(
                        blank=True, max_length=425, null=True, verbose_name="算法名称"
                    ),
                ),
                (
                    "paramname",
                    models.CharField(
                        blank=True, max_length=420, null=True, verbose_name="参数名称"
                    ),
                ),
                (
                    "paramvalue",
                    models.CharField(
                        blank=True, max_length=580, null=True, verbose_name="参数值"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="参数描述"),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatedat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "kwkwisactive",
                    models.BooleanField(blank=True, null=True, verbose_name="是否启用"),
                ),
                (
                    "videotypeid",
                    models.CharField(
                        blank=True,
                        max_length=565,
                        null=True,
                        verbose_name="视频类型ID关联字段指向视频类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频推荐算法参数表",
                "verbose_name_plural": "视频推荐算法参数表",
                "db_table": "videorecommendationparams",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videorelatedcontent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=470, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "contentid",
                    models.CharField(
                        blank=True, max_length=785, null=True, verbose_name="关联内容ID"
                    ),
                ),
                (
                    "contenttype",
                    models.TextField(blank=True, null=True, verbose_name="内容类型"),
                ),
                (
                    "relatedtime",
                    models.CharField(
                        blank=True, max_length=915, null=True, verbose_name="关联时间"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=515, null=True, verbose_name="状态"
                    ),
                ),
                (
                    "creatkwkworid",
                    models.CharField(
                        blank=True,
                        max_length=655,
                        null=True,
                        verbose_name="关联创建者ID",
                    ),
                ),
                (
                    "creationtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "modkwkwificationtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="修改时间"
                    ),
                ),
                (
                    "videotablevideoname",
                    models.CharField(
                        blank=True,
                        max_length=750,
                        null=True,
                        verbose_name="视频名称关联字段视频名假设为VideoTable关联字段为视频名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频关联内容表",
                "verbose_name_plural": "视频关联内容表",
                "db_table": "videorelatedcontent",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoshare",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=945, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=860, null=True, verbose_name="关联用户ID"
                    ),
                ),
                (
                    "sharetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="分享时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=800, null=True, verbose_name="视频标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="视频描述"),
                ),
                (
                    "thumbnailurl",
                    models.URLField(blank=True, null=True, verbose_name="缩略图URL"),
                ),
                (
                    "viewcount",
                    models.CharField(
                        blank=True, max_length=560, null=True, verbose_name="观看次数"
                    ),
                ),
                (
                    "likecount",
                    models.CharField(
                        blank=True, max_length=935, null=True, verbose_name="点赞次数"
                    ),
                ),
                (
                    "commentcount",
                    models.TextField(blank=True, null=True, verbose_name="评论次数"),
                ),
                (
                    "sharestatus",
                    models.CharField(
                        blank=True,
                        max_length=730,
                        null=True,
                        verbose_name="分享状态例如已分享、已删除",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频分享表",
                "verbose_name_plural": "视频分享表",
                "db_table": "videoshare",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videotag",
            fields=[
                (
                    "tagid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="标签ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tagname",
                    models.CharField(
                        blank=True, max_length=975, null=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "videoid",
                    models.CharField(
                        blank=True,
                        max_length=540,
                        null=True,
                        verbose_name="视频ID关联字段指向视频中的视频ID",
                    ),
                ),
                (
                    "createtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "kwkwisactive",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否激活用于标记标签是否可用",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="标签描述"),
                ),
                (
                    "creatkwkworid",
                    models.CharField(
                        blank=True,
                        max_length=430,
                        null=True,
                        verbose_name="创建者ID关联字段指向用户中的用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频标签表",
                "verbose_name_plural": "视频标签表",
                "db_table": "videotag",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videotranscodkwkwingtkwkwask",
            fields=[
                (
                    "tkwkwaskid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="任务ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=940, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "sourcepath",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="58143",
                        verbose_name="源视频路径",
                    ),
                ),
                (
                    "targetkwkwfkwkwormat",
                    models.CharField(
                        blank=True, max_length=625, null=True, verbose_name="目标格式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=760, null=True, verbose_name="任务状态"
                    ),
                ),
                (
                    "progress",
                    models.CharField(
                        blank=True, max_length=540, null=True, verbose_name="任务进度"
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatedat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=835, null=True, verbose_name="关联用户ID"
                    ),
                ),
                (
                    "prikwkwority",
                    models.CharField(
                        blank=True, max_length=405, null=True, verbose_name="任务优先级"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频转码任务表",
                "verbose_name_plural": "视频转码任务表",
                "db_table": "videotranscodkwkwingtkwkwask",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videouploader",
            fields=[
                (
                    "videocategkwkworyid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="视频分类ID",
                    ),
                ),
                (
                    "videoid",
                    models.CharField(
                        auto_created=True,
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="视频ID",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=890, null=True, verbose_name="关联用户ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=770, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name="电子邮件"
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True, max_length=860, null=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "uploadtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="上传时间"
                    ),
                ),
                (
                    "videotitle",
                    models.CharField(
                        blank=True, max_length=715, null=True, verbose_name="视频标题"
                    ),
                ),
                (
                    "videodescription",
                    models.TextField(blank=True, null=True, verbose_name="视频描述"),
                ),
                (
                    "videostatus",
                    models.CharField(
                        blank=True,
                        max_length=950,
                        null=True,
                        verbose_name="视频状态如审核中、已发布、已删除",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频上传用户表",
                "verbose_name_plural": "视频上传用户表",
                "db_table": "videouploader",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videoviewduration",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True, max_length=700, null=True, verbose_name="关联视频ID"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=445, null=True, verbose_name="关联用户ID"
                    ),
                ),
                (
                    "viewstarttime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="观看开始时间"
                    ),
                ),
                (
                    "viewendtime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="观看结束时间"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=720, null=True, verbose_name="观看时长秒"
                    ),
                ),
                (
                    "devicetype",
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name="设备类型"
                    ),
                ),
                (
                    "viewlocation",
                    models.CharField(
                        blank=True, max_length=675, null=True, verbose_name="观看地点"
                    ),
                ),
                (
                    "netwkwkworktype",
                    models.CharField(
                        blank=True, max_length=470, null=True, verbose_name="网络类型"
                    ),
                ),
                (
                    "kwkwiscompleted",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否观看完成0未完成1已完成"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频观看时长统计表",
                "verbose_name_plural": "视频观看时长统计表",
                "db_table": "videoviewduration",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="mc_videowatermarkinfo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "videoid",
                    models.CharField(
                        blank=True,
                        max_length=930,
                        null=True,
                        verbose_name="视频ID关联视频",
                    ),
                ),
                (
                    "watermarktext",
                    models.TextField(blank=True, null=True, verbose_name="水印文本"),
                ),
                (
                    "watermarkposition",
                    models.CharField(
                        blank=True,
                        max_length=620,
                        null=True,
                        verbose_name="水印位置如左上角、右下角等",
                    ),
                ),
                (
                    "watermarksize",
                    models.CharField(
                        blank=True,
                        max_length=905,
                        null=True,
                        verbose_name="水印大小如百分比或像素值",
                    ),
                ),
                (
                    "watermarkopacity",
                    models.CharField(
                        blank=True,
                        max_length=960,
                        null=True,
                        verbose_name="水印透明度0100%",
                    ),
                ),
                (
                    "createdat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updatedat",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "kwkwisactive",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="是否激活用于控制水印是否生效如0为未激活1为激活",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频水印信息表",
                "verbose_name_plural": "视频水印信息表",
                "db_table": "videowatermarkinfo",
                "managed": True,
            },
        ),
    ]
